language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3

before_install:
  # Install Imagick
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - composer test
